version: "3.9"
services:
  myapi:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ecommerce_api
    working_dir: /app
    command: "npm run dev"
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - avanade

  db:

    image: mysql:5.7
    container_name: ecommerce-db
    volumes:
      - type: bind
        source: $HOME/data-mysql
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ecommerce-api
      - MYSQL_USER=ecommerce-api
      - MYSQL_PASSWORD=api-commerce
      - MYSQL_DATABASE=ecommerce_api
      - MYSQL_USER=ecommerce-api
      - MYSQL_PASSWORD=api-commerce
    networks:
      - avanade

networks:
  avanade:
    external:
      name: avanade
