version: "3.4"
services:
  myapi:
    image: encinecarlos-node
    container_name: node-api-ts
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - ENV=local
    environment:
      - ENV=local
    ports:
      - "8000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - avanade

  db:
    image: mysql
    restart: on-failure:3
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ecommerce-api
      - MYSQL_DATABASE=ecommerce_api
    networks:
      - avanade

networks:
  avanade:
    external:
      name: avanade
