version: "3.9"
services:
  myapi:
    image: encinecarlos-node
    container_name: ecommerce-api
    environment:
      - ENV=dev
    ports:
      - "8000:3000"
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - avanade

  db:
    image: mysql
    restart: on-failure:3
    volumes:
      - type: bind
        source: $HOME/data
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    # command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=ecommerce-api
      - MYSQL_DATABASE=ecommerce_api
      - MYSQL_USER=ecommerce-api
      - MYSQL_PASSWORD=api-commerce
    networks:
      - avanade

networks:
  avanade:
    external:
      name: avanade
