version: "3.4"
services:
  myapi:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: ecommerce_api
    working_dir: /app
    command: "npm run dev"
    ports:
      - "3000:3000"
    expose:
      - 3306
    volumes:
      - type: bind
        source: ./app
        target: /app
    networks:
      - avanade

  db:
    image: mysql:5.7
    restart: on-failure
    container_name: ecommerce-db
    volumes:
      - type: bind
        source: $HOME/data-mysql
        target: /var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: api
      MYSQL_DATABASE: db_api
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    networks:
      - avanade

  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - avanade

networks:
  avanade:
    external:
      name: avanade
